# Generated by Django 2.1.3 on 2019-04-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190407_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
